added INSTALL.md
Kaholo/Kaholo-plugin-github pull request #18
Opened 2022-03-25 04:33 UTC by kenskyfish

2022-03-25 08:30 UTC, graddaniel requested changes

2022-03-25 08:30 UTC, graddaniel commented on INSTALL.md
> +1. Create a flat zip file of the code and logo.
Should all these points be ones?

2022-03-25 08:33 UTC, graddaniel approved these changes

2023-07-01 13:23 UTC, kenskyfish commented
Too old to matter now

2023-07-01 13:23 UTC, closed without merging